// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class AccountCashoutResponse;
@class AccountInfo;
@class AccountResponse;
@class BlockInfo;
@class ChainState;
@class DailyTotalTrx;
@class FollowerListInfo;
@class FollowingListInfo;
@class PostResponse;
@class StatByHour;
@class TrxInfo;
@class VoterOfPost;
@class WitnessResponse;
@class account_name;
@class beneficiary_route_type;
@class coin;
@class dynamic_properties;
@class follower_created_order;
@class following_created_order;
@class post_created_order;
@class public_key_type;
@class reply_created_order;
@class sha256;
@class signed_block;
@class signed_transaction;
@class time_point_sec;
@class transaction_receipt_with_info;
@class transaction_wrapper;
@class user_post_create_order;
@class vest;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - GrpcRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface GrpcRoot : GPBRootObject
@end

#pragma mark - GetTableContentRequest

typedef GPB_ENUM(GetTableContentRequest_FieldNumber) {
  GetTableContentRequest_FieldNumber_Owner = 1,
  GetTableContentRequest_FieldNumber_Contract = 2,
  GetTableContentRequest_FieldNumber_Table = 3,
  GetTableContentRequest_FieldNumber_Field = 4,
  GetTableContentRequest_FieldNumber_Begin = 5,
  GetTableContentRequest_FieldNumber_Count = 6,
  GetTableContentRequest_FieldNumber_Reverse = 7,
};

@interface GetTableContentRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *owner;

@property(nonatomic, readwrite, copy, null_resettable) NSString *contract;

@property(nonatomic, readwrite, copy, null_resettable) NSString *table;

@property(nonatomic, readwrite, copy, null_resettable) NSString *field;

@property(nonatomic, readwrite, copy, null_resettable) NSString *begin;

@property(nonatomic, readwrite) uint32_t count;

@property(nonatomic, readwrite) BOOL reverse;

@end

#pragma mark - TableContentResponse

typedef GPB_ENUM(TableContentResponse_FieldNumber) {
  TableContentResponse_FieldNumber_TableContent = 1,
};

@interface TableContentResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *tableContent;

@end

#pragma mark - GetAccountByNameRequest

typedef GPB_ENUM(GetAccountByNameRequest_FieldNumber) {
  GetAccountByNameRequest_FieldNumber_AccountName = 1,
};

@interface GetAccountByNameRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) account_name *accountName;
/** Test to see if @c accountName has been set. */
@property(nonatomic, readwrite) BOOL hasAccountName;

@end

#pragma mark - GetAccountCashoutRequest

typedef GPB_ENUM(GetAccountCashoutRequest_FieldNumber) {
  GetAccountCashoutRequest_FieldNumber_AccountName = 1,
  GetAccountCashoutRequest_FieldNumber_PostId = 2,
};

@interface GetAccountCashoutRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) account_name *accountName;
/** Test to see if @c accountName has been set. */
@property(nonatomic, readwrite) BOOL hasAccountName;

@property(nonatomic, readwrite) uint64_t postId;

@end

#pragma mark - AccountCashoutResponse

typedef GPB_ENUM(AccountCashoutResponse_FieldNumber) {
  AccountCashoutResponse_FieldNumber_AccountName = 1,
  AccountCashoutResponse_FieldNumber_Reward = 2,
};

@interface AccountCashoutResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) account_name *accountName;
/** Test to see if @c accountName has been set. */
@property(nonatomic, readwrite) BOOL hasAccountName;

@property(nonatomic, readwrite, strong, null_resettable) vest *reward;
/** Test to see if @c reward has been set. */
@property(nonatomic, readwrite) BOOL hasReward;

@end

#pragma mark - GetBlockCashoutRequest

typedef GPB_ENUM(GetBlockCashoutRequest_FieldNumber) {
  GetBlockCashoutRequest_FieldNumber_BlockHeight = 1,
};

@interface GetBlockCashoutRequest : GPBMessage

@property(nonatomic, readwrite) uint64_t blockHeight;

@end

#pragma mark - BlockCashoutResponse

typedef GPB_ENUM(BlockCashoutResponse_FieldNumber) {
  BlockCashoutResponse_FieldNumber_CashoutListArray = 1,
};

@interface BlockCashoutResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<AccountCashoutResponse*> *cashoutListArray;
/** The number of items in @c cashoutListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger cashoutListArray_Count;

@end

#pragma mark - GetAccountRewardByNameRequest

typedef GPB_ENUM(GetAccountRewardByNameRequest_FieldNumber) {
  GetAccountRewardByNameRequest_FieldNumber_AccountName = 1,
};

@interface GetAccountRewardByNameRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) account_name *accountName;
/** Test to see if @c accountName has been set. */
@property(nonatomic, readwrite) BOOL hasAccountName;

@end

#pragma mark - AccountRewardResponse

typedef GPB_ENUM(AccountRewardResponse_FieldNumber) {
  AccountRewardResponse_FieldNumber_AccountName = 1,
  AccountRewardResponse_FieldNumber_Reward = 2,
};

@interface AccountRewardResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) account_name *accountName;
/** Test to see if @c accountName has been set. */
@property(nonatomic, readwrite) BOOL hasAccountName;

@property(nonatomic, readwrite, strong, null_resettable) vest *reward;
/** Test to see if @c reward has been set. */
@property(nonatomic, readwrite) BOOL hasReward;

@end

#pragma mark - AccountInfo

typedef GPB_ENUM(AccountInfo_FieldNumber) {
  AccountInfo_FieldNumber_AccountName = 1,
  AccountInfo_FieldNumber_Coin = 2,
  AccountInfo_FieldNumber_Vest = 3,
  AccountInfo_FieldNumber_PublicKey = 4,
  AccountInfo_FieldNumber_CreatedTime = 5,
  AccountInfo_FieldNumber_Witness = 6,
  AccountInfo_FieldNumber_PostCount = 7,
  AccountInfo_FieldNumber_FollowerCount = 8,
  AccountInfo_FieldNumber_FollowingCount = 9,
  AccountInfo_FieldNumber_TrxCount = 10,
  AccountInfo_FieldNumber_VotePower = 11,
};

@interface AccountInfo : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) account_name *accountName;
/** Test to see if @c accountName has been set. */
@property(nonatomic, readwrite) BOOL hasAccountName;

@property(nonatomic, readwrite, strong, null_resettable) coin *coin;
/** Test to see if @c coin has been set. */
@property(nonatomic, readwrite) BOOL hasCoin;

@property(nonatomic, readwrite, strong, null_resettable) vest *vest;
/** Test to see if @c vest has been set. */
@property(nonatomic, readwrite) BOOL hasVest;

@property(nonatomic, readwrite, strong, null_resettable) public_key_type *publicKey;
/** Test to see if @c publicKey has been set. */
@property(nonatomic, readwrite) BOOL hasPublicKey;

@property(nonatomic, readwrite, strong, null_resettable) time_point_sec *createdTime;
/** Test to see if @c createdTime has been set. */
@property(nonatomic, readwrite) BOOL hasCreatedTime;

@property(nonatomic, readwrite, strong, null_resettable) WitnessResponse *witness;
/** Test to see if @c witness has been set. */
@property(nonatomic, readwrite) BOOL hasWitness;

@property(nonatomic, readwrite) uint32_t postCount;

@property(nonatomic, readwrite) uint32_t followerCount;

@property(nonatomic, readwrite) uint32_t followingCount;

@property(nonatomic, readwrite) uint32_t trxCount;

@property(nonatomic, readwrite) uint32_t votePower;

@end

#pragma mark - AccountResponse

typedef GPB_ENUM(AccountResponse_FieldNumber) {
  AccountResponse_FieldNumber_Info = 1,
  AccountResponse_FieldNumber_State = 2,
};

@interface AccountResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) AccountInfo *info;
/** Test to see if @c info has been set. */
@property(nonatomic, readwrite) BOOL hasInfo;

@property(nonatomic, readwrite, strong, null_resettable) ChainState *state;
/** Test to see if @c state has been set. */
@property(nonatomic, readwrite) BOOL hasState;

@end

#pragma mark - GetFollowerListByNameRequest

typedef GPB_ENUM(GetFollowerListByNameRequest_FieldNumber) {
  GetFollowerListByNameRequest_FieldNumber_Start = 1,
  GetFollowerListByNameRequest_FieldNumber_End = 2,
  GetFollowerListByNameRequest_FieldNumber_Limit = 3,
  GetFollowerListByNameRequest_FieldNumber_LastOrder = 4,
};

@interface GetFollowerListByNameRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) follower_created_order *start;
/** Test to see if @c start has been set. */
@property(nonatomic, readwrite) BOOL hasStart;

@property(nonatomic, readwrite, strong, null_resettable) follower_created_order *end;
/** Test to see if @c end has been set. */
@property(nonatomic, readwrite) BOOL hasEnd;

@property(nonatomic, readwrite) uint32_t limit;

@property(nonatomic, readwrite, strong, null_resettable) follower_created_order *lastOrder;
/** Test to see if @c lastOrder has been set. */
@property(nonatomic, readwrite) BOOL hasLastOrder;

@end

#pragma mark - FollowerListInfo

typedef GPB_ENUM(FollowerListInfo_FieldNumber) {
  FollowerListInfo_FieldNumber_Account = 1,
  FollowerListInfo_FieldNumber_CreateOrder = 2,
};

@interface FollowerListInfo : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) AccountResponse *account;
/** Test to see if @c account has been set. */
@property(nonatomic, readwrite) BOOL hasAccount;

@property(nonatomic, readwrite, strong, null_resettable) follower_created_order *createOrder;
/** Test to see if @c createOrder has been set. */
@property(nonatomic, readwrite) BOOL hasCreateOrder;

@end

#pragma mark - GetFollowerListByNameResponse

typedef GPB_ENUM(GetFollowerListByNameResponse_FieldNumber) {
  GetFollowerListByNameResponse_FieldNumber_FollowerListArray = 1,
};

@interface GetFollowerListByNameResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<FollowerListInfo*> *followerListArray;
/** The number of items in @c followerListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger followerListArray_Count;

@end

#pragma mark - GetFollowingListByNameRequest

typedef GPB_ENUM(GetFollowingListByNameRequest_FieldNumber) {
  GetFollowingListByNameRequest_FieldNumber_Start = 1,
  GetFollowingListByNameRequest_FieldNumber_End = 2,
  GetFollowingListByNameRequest_FieldNumber_Limit = 3,
  GetFollowingListByNameRequest_FieldNumber_LastOrder = 4,
};

@interface GetFollowingListByNameRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) following_created_order *start;
/** Test to see if @c start has been set. */
@property(nonatomic, readwrite) BOOL hasStart;

@property(nonatomic, readwrite, strong, null_resettable) following_created_order *end;
/** Test to see if @c end has been set. */
@property(nonatomic, readwrite) BOOL hasEnd;

@property(nonatomic, readwrite) uint32_t limit;

@property(nonatomic, readwrite, strong, null_resettable) following_created_order *lastOrder;
/** Test to see if @c lastOrder has been set. */
@property(nonatomic, readwrite) BOOL hasLastOrder;

@end

#pragma mark - FollowingListInfo

typedef GPB_ENUM(FollowingListInfo_FieldNumber) {
  FollowingListInfo_FieldNumber_Account = 1,
  FollowingListInfo_FieldNumber_CreateOrder = 2,
};

@interface FollowingListInfo : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) AccountResponse *account;
/** Test to see if @c account has been set. */
@property(nonatomic, readwrite) BOOL hasAccount;

@property(nonatomic, readwrite, strong, null_resettable) following_created_order *createOrder;
/** Test to see if @c createOrder has been set. */
@property(nonatomic, readwrite) BOOL hasCreateOrder;

@end

#pragma mark - GetFollowingListByNameResponse

typedef GPB_ENUM(GetFollowingListByNameResponse_FieldNumber) {
  GetFollowingListByNameResponse_FieldNumber_FollowingListArray = 1,
};

@interface GetFollowingListByNameResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<FollowingListInfo*> *followingListArray;
/** The number of items in @c followingListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger followingListArray_Count;

@end

#pragma mark - GetFollowCountByNameRequest

typedef GPB_ENUM(GetFollowCountByNameRequest_FieldNumber) {
  GetFollowCountByNameRequest_FieldNumber_AccountName = 1,
};

@interface GetFollowCountByNameRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) account_name *accountName;
/** Test to see if @c accountName has been set. */
@property(nonatomic, readwrite) BOOL hasAccountName;

@end

#pragma mark - GetFollowCountByNameResponse

typedef GPB_ENUM(GetFollowCountByNameResponse_FieldNumber) {
  GetFollowCountByNameResponse_FieldNumber_FerCnt = 1,
  GetFollowCountByNameResponse_FieldNumber_FingCnt = 2,
};

@interface GetFollowCountByNameResponse : GPBMessage

@property(nonatomic, readwrite) uint32_t ferCnt;

@property(nonatomic, readwrite) uint32_t fingCnt;

@end

#pragma mark - WitnessResponse

typedef GPB_ENUM(WitnessResponse_FieldNumber) {
  WitnessResponse_FieldNumber_Owner = 1,
  WitnessResponse_FieldNumber_RunningVersion = 2,
  WitnessResponse_FieldNumber_CreatedTime = 3,
  WitnessResponse_FieldNumber_URL = 4,
  WitnessResponse_FieldNumber_LastConfirmedBlockNum = 5,
  WitnessResponse_FieldNumber_TotalMissed = 6,
  WitnessResponse_FieldNumber_VoteCount = 7,
  WitnessResponse_FieldNumber_SigningKey = 8,
  WitnessResponse_FieldNumber_LastWork = 9,
};

@interface WitnessResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) account_name *owner;
/** Test to see if @c owner has been set. */
@property(nonatomic, readwrite) BOOL hasOwner;

@property(nonatomic, readwrite, strong, null_resettable) time_point_sec *createdTime;
/** Test to see if @c createdTime has been set. */
@property(nonatomic, readwrite) BOOL hasCreatedTime;

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@property(nonatomic, readwrite) uint32_t lastConfirmedBlockNum;

@property(nonatomic, readwrite) uint32_t totalMissed;

@property(nonatomic, readwrite) uint64_t voteCount;

@property(nonatomic, readwrite, strong, null_resettable) public_key_type *signingKey;
/** Test to see if @c signingKey has been set. */
@property(nonatomic, readwrite) BOOL hasSigningKey;

@property(nonatomic, readwrite, strong, null_resettable) sha256 *lastWork;
/** Test to see if @c lastWork has been set. */
@property(nonatomic, readwrite) BOOL hasLastWork;

@property(nonatomic, readwrite) uint32_t runningVersion;

@end

#pragma mark - GetWitnessListRequest

typedef GPB_ENUM(GetWitnessListRequest_FieldNumber) {
  GetWitnessListRequest_FieldNumber_Start = 1,
  GetWitnessListRequest_FieldNumber_Limit = 2,
};

@interface GetWitnessListRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) account_name *start;
/** Test to see if @c start has been set. */
@property(nonatomic, readwrite) BOOL hasStart;

@property(nonatomic, readwrite) uint32_t limit;

@end

#pragma mark - GetWitnessListResponse

typedef GPB_ENUM(GetWitnessListResponse_FieldNumber) {
  GetWitnessListResponse_FieldNumber_WitnessListArray = 1,
};

@interface GetWitnessListResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<WitnessResponse*> *witnessListArray;
/** The number of items in @c witnessListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger witnessListArray_Count;

@end

#pragma mark - PostResponse

typedef GPB_ENUM(PostResponse_FieldNumber) {
  PostResponse_FieldNumber_PostId = 1,
  PostResponse_FieldNumber_Category = 2,
  PostResponse_FieldNumber_ParentAuthor = 3,
  PostResponse_FieldNumber_Author = 5,
  PostResponse_FieldNumber_Title = 7,
  PostResponse_FieldNumber_Body = 8,
  PostResponse_FieldNumber_Created = 11,
  PostResponse_FieldNumber_LastPayout = 13,
  PostResponse_FieldNumber_Depth = 14,
  PostResponse_FieldNumber_Children = 15,
  PostResponse_FieldNumber_RootId = 16,
  PostResponse_FieldNumber_ParentId = 17,
  PostResponse_FieldNumber_TagsArray = 18,
  PostResponse_FieldNumber_BeneficiariesArray = 19,
  PostResponse_FieldNumber_VoteCnt = 20,
  PostResponse_FieldNumber_WeightedVp = 21,
  PostResponse_FieldNumber_Rewards = 22,
  PostResponse_FieldNumber_DappRewards = 23,
  PostResponse_FieldNumber_CashoutInterval = 24,
  PostResponse_FieldNumber_GlobalRewards = 25,
  PostResponse_FieldNumber_GlobalWeightedVp = 26,
};

@interface PostResponse : GPBMessage

@property(nonatomic, readwrite) uint64_t postId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *category;

@property(nonatomic, readwrite, strong, null_resettable) account_name *parentAuthor;
/** Test to see if @c parentAuthor has been set. */
@property(nonatomic, readwrite) BOOL hasParentAuthor;

@property(nonatomic, readwrite, strong, null_resettable) account_name *author;
/** Test to see if @c author has been set. */
@property(nonatomic, readwrite) BOOL hasAuthor;

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite, copy, null_resettable) NSString *body;

@property(nonatomic, readwrite, strong, null_resettable) time_point_sec *created;
/** Test to see if @c created has been set. */
@property(nonatomic, readwrite) BOOL hasCreated;

@property(nonatomic, readwrite, strong, null_resettable) time_point_sec *lastPayout;
/** Test to see if @c lastPayout has been set. */
@property(nonatomic, readwrite) BOOL hasLastPayout;

@property(nonatomic, readwrite) uint32_t depth;

@property(nonatomic, readwrite) uint32_t children;

@property(nonatomic, readwrite) uint64_t rootId;

@property(nonatomic, readwrite) uint64_t parentId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *tagsArray;
/** The number of items in @c tagsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tagsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<beneficiary_route_type*> *beneficiariesArray;
/** The number of items in @c beneficiariesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger beneficiariesArray_Count;

@property(nonatomic, readwrite) uint64_t voteCnt;

@property(nonatomic, readwrite) uint64_t weightedVp;

@property(nonatomic, readwrite, strong, null_resettable) vest *rewards;
/** Test to see if @c rewards has been set. */
@property(nonatomic, readwrite) BOOL hasRewards;

@property(nonatomic, readwrite, strong, null_resettable) vest *dappRewards;
/** Test to see if @c dappRewards has been set. */
@property(nonatomic, readwrite) BOOL hasDappRewards;

@property(nonatomic, readwrite) uint64_t cashoutInterval;

@property(nonatomic, readwrite, strong, null_resettable) vest *globalRewards;
/** Test to see if @c globalRewards has been set. */
@property(nonatomic, readwrite) BOOL hasGlobalRewards;

@property(nonatomic, readwrite) uint64_t globalWeightedVp;

@end

#pragma mark - GetPostListByCreatedRequest

typedef GPB_ENUM(GetPostListByCreatedRequest_FieldNumber) {
  GetPostListByCreatedRequest_FieldNumber_Start = 1,
  GetPostListByCreatedRequest_FieldNumber_End = 2,
  GetPostListByCreatedRequest_FieldNumber_Limit = 3,
};

@interface GetPostListByCreatedRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) post_created_order *start;
/** Test to see if @c start has been set. */
@property(nonatomic, readwrite) BOOL hasStart;

@property(nonatomic, readwrite, strong, null_resettable) post_created_order *end;
/** Test to see if @c end has been set. */
@property(nonatomic, readwrite) BOOL hasEnd;

@property(nonatomic, readwrite) uint32_t limit;

@end

#pragma mark - GetPostListByCreatedResponse

typedef GPB_ENUM(GetPostListByCreatedResponse_FieldNumber) {
  GetPostListByCreatedResponse_FieldNumber_PostListArray = 1,
};

@interface GetPostListByCreatedResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PostResponse*> *postListArray;
/** The number of items in @c postListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger postListArray_Count;

@end

#pragma mark - GetReplyListByPostIdRequest

typedef GPB_ENUM(GetReplyListByPostIdRequest_FieldNumber) {
  GetReplyListByPostIdRequest_FieldNumber_Start = 1,
  GetReplyListByPostIdRequest_FieldNumber_End = 2,
  GetReplyListByPostIdRequest_FieldNumber_Limit = 3,
};

@interface GetReplyListByPostIdRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) reply_created_order *start;
/** Test to see if @c start has been set. */
@property(nonatomic, readwrite) BOOL hasStart;

@property(nonatomic, readwrite, strong, null_resettable) reply_created_order *end;
/** Test to see if @c end has been set. */
@property(nonatomic, readwrite) BOOL hasEnd;

@property(nonatomic, readwrite) uint32_t limit;

@end

#pragma mark - GetReplyListByPostIdResponse

typedef GPB_ENUM(GetReplyListByPostIdResponse_FieldNumber) {
  GetReplyListByPostIdResponse_FieldNumber_ReplyListArray = 1,
};

@interface GetReplyListByPostIdResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PostResponse*> *replyListArray;
/** The number of items in @c replyListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger replyListArray_Count;

@end

#pragma mark - GetBlockTransactionsByNumRequest

typedef GPB_ENUM(GetBlockTransactionsByNumRequest_FieldNumber) {
  GetBlockTransactionsByNumRequest_FieldNumber_BlockNum = 1,
  GetBlockTransactionsByNumRequest_FieldNumber_Start = 2,
  GetBlockTransactionsByNumRequest_FieldNumber_Limit = 3,
};

@interface GetBlockTransactionsByNumRequest : GPBMessage

@property(nonatomic, readwrite) uint32_t blockNum;

@property(nonatomic, readwrite) uint32_t start;

@property(nonatomic, readwrite) uint32_t limit;

@end

#pragma mark - GetBlockTransactionsByNumResponse

typedef GPB_ENUM(GetBlockTransactionsByNumResponse_FieldNumber) {
  GetBlockTransactionsByNumResponse_FieldNumber_TransactionsArray = 1,
};

@interface GetBlockTransactionsByNumResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<signed_transaction*> *transactionsArray;
/** The number of items in @c transactionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger transactionsArray_Count;

@end

#pragma mark - GetChainStateResponse

typedef GPB_ENUM(GetChainStateResponse_FieldNumber) {
  GetChainStateResponse_FieldNumber_State = 1,
};

@interface GetChainStateResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ChainState *state;
/** Test to see if @c state has been set. */
@property(nonatomic, readwrite) BOOL hasState;

@end

#pragma mark - GetStatResponse

typedef GPB_ENUM(GetStatResponse_FieldNumber) {
  GetStatResponse_FieldNumber_State = 1,
  GetStatResponse_FieldNumber_DailyTrxCountsArray = 2,
};

@interface GetStatResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ChainState *state;
/** Test to see if @c state has been set. */
@property(nonatomic, readwrite) BOOL hasState;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *dailyTrxCountsArray;
/** The number of items in @c dailyTrxCountsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger dailyTrxCountsArray_Count;

@end

#pragma mark - BroadcastTrxRequest

typedef GPB_ENUM(BroadcastTrxRequest_FieldNumber) {
  BroadcastTrxRequest_FieldNumber_Transaction = 1,
  BroadcastTrxRequest_FieldNumber_OnlyDeliver = 2,
};

@interface BroadcastTrxRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) signed_transaction *transaction;
/** Test to see if @c transaction has been set. */
@property(nonatomic, readwrite) BOOL hasTransaction;

@property(nonatomic, readwrite) BOOL onlyDeliver;

@end

#pragma mark - BroadcastTrxResponse

typedef GPB_ENUM(BroadcastTrxResponse_FieldNumber) {
  BroadcastTrxResponse_FieldNumber_Invoice = 1,
  BroadcastTrxResponse_FieldNumber_Status = 2,
  BroadcastTrxResponse_FieldNumber_Msg = 3,
};

@interface BroadcastTrxResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) transaction_receipt_with_info *invoice;
/** Test to see if @c invoice has been set. */
@property(nonatomic, readwrite) BOOL hasInvoice;

@property(nonatomic, readwrite) uint32_t status;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;

@end

#pragma mark - NonParamsRequest

@interface NonParamsRequest : GPBMessage

@end

#pragma mark - CallResponse

typedef GPB_ENUM(CallResponse_FieldNumber) {
  CallResponse_FieldNumber_Result = 1,
  CallResponse_FieldNumber_ExecuteErr = 2,
  CallResponse_FieldNumber_EstimateGas = 3,
};

@interface CallResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *result;

@property(nonatomic, readwrite, copy, null_resettable) NSString *executeErr;

@property(nonatomic, readwrite, copy, null_resettable) NSString *estimateGas;

@end

#pragma mark - ChainState

typedef GPB_ENUM(ChainState_FieldNumber) {
  ChainState_FieldNumber_LastIrreversibleBlockNumber = 1,
  ChainState_FieldNumber_LastIrreversibleBlockTime = 2,
  ChainState_FieldNumber_Dgpo = 3,
};

@interface ChainState : GPBMessage

@property(nonatomic, readwrite) uint64_t lastIrreversibleBlockNumber;

@property(nonatomic, readwrite) uint64_t lastIrreversibleBlockTime;

@property(nonatomic, readwrite, strong, null_resettable) dynamic_properties *dgpo;
/** Test to see if @c dgpo has been set. */
@property(nonatomic, readwrite) BOOL hasDgpo;

@end

#pragma mark - GetBlockListRequest

typedef GPB_ENUM(GetBlockListRequest_FieldNumber) {
  GetBlockListRequest_FieldNumber_Start = 1,
  GetBlockListRequest_FieldNumber_End = 2,
  GetBlockListRequest_FieldNumber_Limit = 3,
};

@interface GetBlockListRequest : GPBMessage

@property(nonatomic, readwrite) uint64_t start;

@property(nonatomic, readwrite) uint64_t end;

@property(nonatomic, readwrite) uint32_t limit;

@end

#pragma mark - BlockInfo

typedef GPB_ENUM(BlockInfo_FieldNumber) {
  BlockInfo_FieldNumber_Timestamp = 1,
  BlockInfo_FieldNumber_BlockHeight = 2,
  BlockInfo_FieldNumber_TrxCount = 3,
  BlockInfo_FieldNumber_Witness = 4,
  BlockInfo_FieldNumber_BlockId = 5,
  BlockInfo_FieldNumber_PreId = 6,
  BlockInfo_FieldNumber_BlockSize = 7,
};

@interface BlockInfo : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) time_point_sec *timestamp;
/** Test to see if @c timestamp has been set. */
@property(nonatomic, readwrite) BOOL hasTimestamp;

@property(nonatomic, readwrite) uint64_t blockHeight;

@property(nonatomic, readwrite) uint32_t trxCount;

@property(nonatomic, readwrite, strong, null_resettable) account_name *witness;
/** Test to see if @c witness has been set. */
@property(nonatomic, readwrite) BOOL hasWitness;

@property(nonatomic, readwrite, strong, null_resettable) sha256 *blockId;
/** Test to see if @c blockId has been set. */
@property(nonatomic, readwrite) BOOL hasBlockId;

@property(nonatomic, readwrite, strong, null_resettable) sha256 *preId;
/** Test to see if @c preId has been set. */
@property(nonatomic, readwrite) BOOL hasPreId;

@property(nonatomic, readwrite) uint32_t blockSize;

@end

#pragma mark - GetBlockListResponse

typedef GPB_ENUM(GetBlockListResponse_FieldNumber) {
  GetBlockListResponse_FieldNumber_BlocksArray = 1,
};

@interface GetBlockListResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<BlockInfo*> *blocksArray;
/** The number of items in @c blocksArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger blocksArray_Count;

@end

#pragma mark - GetSignedBlockRequest

typedef GPB_ENUM(GetSignedBlockRequest_FieldNumber) {
  GetSignedBlockRequest_FieldNumber_Start = 1,
};

@interface GetSignedBlockRequest : GPBMessage

@property(nonatomic, readwrite) uint64_t start;

@end

#pragma mark - GetSignedBlockResponse

typedef GPB_ENUM(GetSignedBlockResponse_FieldNumber) {
  GetSignedBlockResponse_FieldNumber_Block = 1,
};

@interface GetSignedBlockResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) signed_block *block;
/** Test to see if @c block has been set. */
@property(nonatomic, readwrite) BOOL hasBlock;

@end

#pragma mark - GetAccountListByBalanceRequest

typedef GPB_ENUM(GetAccountListByBalanceRequest_FieldNumber) {
  GetAccountListByBalanceRequest_FieldNumber_Start = 1,
  GetAccountListByBalanceRequest_FieldNumber_End = 2,
  GetAccountListByBalanceRequest_FieldNumber_LastAccount = 3,
  GetAccountListByBalanceRequest_FieldNumber_Limit = 4,
};

@interface GetAccountListByBalanceRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) coin *start;
/** Test to see if @c start has been set. */
@property(nonatomic, readwrite) BOOL hasStart;

@property(nonatomic, readwrite, strong, null_resettable) coin *end;
/** Test to see if @c end has been set. */
@property(nonatomic, readwrite) BOOL hasEnd;

@property(nonatomic, readwrite, strong, null_resettable) AccountInfo *lastAccount;
/** Test to see if @c lastAccount has been set. */
@property(nonatomic, readwrite) BOOL hasLastAccount;

@property(nonatomic, readwrite) uint32_t limit;

@end

#pragma mark - GetAccountListResponse

typedef GPB_ENUM(GetAccountListResponse_FieldNumber) {
  GetAccountListResponse_FieldNumber_ListArray = 1,
};

@interface GetAccountListResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<AccountResponse*> *listArray;
/** The number of items in @c listArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

#pragma mark - DailyTotalTrx

typedef GPB_ENUM(DailyTotalTrx_FieldNumber) {
  DailyTotalTrx_FieldNumber_Date = 1,
  DailyTotalTrx_FieldNumber_Count = 2,
};

@interface DailyTotalTrx : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) time_point_sec *date;
/** Test to see if @c date has been set. */
@property(nonatomic, readwrite) BOOL hasDate;

@property(nonatomic, readwrite) uint64_t count;

@end

#pragma mark - GetDailyTotalTrxRequest

typedef GPB_ENUM(GetDailyTotalTrxRequest_FieldNumber) {
  GetDailyTotalTrxRequest_FieldNumber_Start = 1,
  GetDailyTotalTrxRequest_FieldNumber_End = 2,
  GetDailyTotalTrxRequest_FieldNumber_LastInfo = 3,
  GetDailyTotalTrxRequest_FieldNumber_Limit = 4,
};

@interface GetDailyTotalTrxRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) time_point_sec *start;
/** Test to see if @c start has been set. */
@property(nonatomic, readwrite) BOOL hasStart;

@property(nonatomic, readwrite, strong, null_resettable) time_point_sec *end;
/** Test to see if @c end has been set. */
@property(nonatomic, readwrite) BOOL hasEnd;

@property(nonatomic, readwrite, strong, null_resettable) DailyTotalTrx *lastInfo;
/** Test to see if @c lastInfo has been set. */
@property(nonatomic, readwrite) BOOL hasLastInfo;

@property(nonatomic, readwrite) uint32_t limit;

@end

#pragma mark - GetDailyTotalTrxResponse

typedef GPB_ENUM(GetDailyTotalTrxResponse_FieldNumber) {
  GetDailyTotalTrxResponse_FieldNumber_ListArray = 1,
};

@interface GetDailyTotalTrxResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DailyTotalTrx*> *listArray;
/** The number of items in @c listArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

#pragma mark - StatByHour

typedef GPB_ENUM(StatByHour_FieldNumber) {
  StatByHour_FieldNumber_Hour = 1,
  StatByHour_FieldNumber_Count = 2,
};

@interface StatByHour : GPBMessage

@property(nonatomic, readwrite) uint32_t hour;

@property(nonatomic, readwrite) uint32_t count;

@end

#pragma mark - TrxStatByHourRequest

typedef GPB_ENUM(TrxStatByHourRequest_FieldNumber) {
  TrxStatByHourRequest_FieldNumber_Hours = 1,
};

@interface TrxStatByHourRequest : GPBMessage

@property(nonatomic, readwrite) uint32_t hours;

@end

#pragma mark - TrxStatByHourResponse

typedef GPB_ENUM(TrxStatByHourResponse_FieldNumber) {
  TrxStatByHourResponse_FieldNumber_StatArray = 1,
};

@interface TrxStatByHourResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<StatByHour*> *statArray;
/** The number of items in @c statArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger statArray_Count;

@end

#pragma mark - TrxInfo

typedef GPB_ENUM(TrxInfo_FieldNumber) {
  TrxInfo_FieldNumber_TrxId = 1,
  TrxInfo_FieldNumber_BlockHeight = 2,
  TrxInfo_FieldNumber_TrxWrap = 3,
  TrxInfo_FieldNumber_BlockTime = 4,
  TrxInfo_FieldNumber_BlockId = 5,
  TrxInfo_FieldNumber_BlkIsIrreversible = 6,
};

@interface TrxInfo : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) sha256 *trxId;
/** Test to see if @c trxId has been set. */
@property(nonatomic, readwrite) BOOL hasTrxId;

@property(nonatomic, readwrite) uint64_t blockHeight;

@property(nonatomic, readwrite, strong, null_resettable) transaction_wrapper *trxWrap;
/** Test to see if @c trxWrap has been set. */
@property(nonatomic, readwrite) BOOL hasTrxWrap;

@property(nonatomic, readwrite, strong, null_resettable) time_point_sec *blockTime;
/** Test to see if @c blockTime has been set. */
@property(nonatomic, readwrite) BOOL hasBlockTime;

@property(nonatomic, readwrite, strong, null_resettable) sha256 *blockId;
/** Test to see if @c blockId has been set. */
@property(nonatomic, readwrite) BOOL hasBlockId;

@property(nonatomic, readwrite) BOOL blkIsIrreversible;

@end

#pragma mark - GetTrxInfoByIdRequest

typedef GPB_ENUM(GetTrxInfoByIdRequest_FieldNumber) {
  GetTrxInfoByIdRequest_FieldNumber_TrxId = 1,
};

@interface GetTrxInfoByIdRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) sha256 *trxId;
/** Test to see if @c trxId has been set. */
@property(nonatomic, readwrite) BOOL hasTrxId;

@end

#pragma mark - GetTrxInfoByIdResponse

typedef GPB_ENUM(GetTrxInfoByIdResponse_FieldNumber) {
  GetTrxInfoByIdResponse_FieldNumber_Info = 1,
};

@interface GetTrxInfoByIdResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) TrxInfo *info;
/** Test to see if @c info has been set. */
@property(nonatomic, readwrite) BOOL hasInfo;

@end

#pragma mark - GetTrxListByTimeRequest

typedef GPB_ENUM(GetTrxListByTimeRequest_FieldNumber) {
  GetTrxListByTimeRequest_FieldNumber_Start = 1,
  GetTrxListByTimeRequest_FieldNumber_End = 2,
  GetTrxListByTimeRequest_FieldNumber_Limit = 3,
  GetTrxListByTimeRequest_FieldNumber_LastInfo = 4,
};

@interface GetTrxListByTimeRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) time_point_sec *start;
/** Test to see if @c start has been set. */
@property(nonatomic, readwrite) BOOL hasStart;

@property(nonatomic, readwrite, strong, null_resettable) time_point_sec *end;
/** Test to see if @c end has been set. */
@property(nonatomic, readwrite) BOOL hasEnd;

@property(nonatomic, readwrite) uint32_t limit;

@property(nonatomic, readwrite, strong, null_resettable) TrxInfo *lastInfo;
/** Test to see if @c lastInfo has been set. */
@property(nonatomic, readwrite) BOOL hasLastInfo;

@end

#pragma mark - GetTrxListByTimeResponse

typedef GPB_ENUM(GetTrxListByTimeResponse_FieldNumber) {
  GetTrxListByTimeResponse_FieldNumber_ListArray = 1,
};

@interface GetTrxListByTimeResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TrxInfo*> *listArray;
/** The number of items in @c listArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

#pragma mark - GetPostListByCreateTimeRequest

typedef GPB_ENUM(GetPostListByCreateTimeRequest_FieldNumber) {
  GetPostListByCreateTimeRequest_FieldNumber_Start = 1,
  GetPostListByCreateTimeRequest_FieldNumber_End = 2,
  GetPostListByCreateTimeRequest_FieldNumber_LastPost = 3,
  GetPostListByCreateTimeRequest_FieldNumber_Limit = 4,
};

@interface GetPostListByCreateTimeRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) time_point_sec *start;
/** Test to see if @c start has been set. */
@property(nonatomic, readwrite) BOOL hasStart;

@property(nonatomic, readwrite, strong, null_resettable) time_point_sec *end;
/** Test to see if @c end has been set. */
@property(nonatomic, readwrite) BOOL hasEnd;

@property(nonatomic, readwrite, strong, null_resettable) PostResponse *lastPost;
/** Test to see if @c lastPost has been set. */
@property(nonatomic, readwrite) BOOL hasLastPost;

@property(nonatomic, readwrite) uint32_t limit;

@end

#pragma mark - GetPostListByCreateTimeResponse

typedef GPB_ENUM(GetPostListByCreateTimeResponse_FieldNumber) {
  GetPostListByCreateTimeResponse_FieldNumber_PostedListArray = 1,
};

@interface GetPostListByCreateTimeResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PostResponse*> *postedListArray;
/** The number of items in @c postedListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger postedListArray_Count;

@end

#pragma mark - GetPostListByNameRequest

typedef GPB_ENUM(GetPostListByNameRequest_FieldNumber) {
  GetPostListByNameRequest_FieldNumber_Start = 1,
  GetPostListByNameRequest_FieldNumber_End = 2,
  GetPostListByNameRequest_FieldNumber_LastPost = 3,
  GetPostListByNameRequest_FieldNumber_Limit = 4,
};

@interface GetPostListByNameRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) user_post_create_order *start;
/** Test to see if @c start has been set. */
@property(nonatomic, readwrite) BOOL hasStart;

@property(nonatomic, readwrite, strong, null_resettable) user_post_create_order *end;
/** Test to see if @c end has been set. */
@property(nonatomic, readwrite) BOOL hasEnd;

@property(nonatomic, readwrite, strong, null_resettable) PostResponse *lastPost;
/** Test to see if @c lastPost has been set. */
@property(nonatomic, readwrite) BOOL hasLastPost;

@property(nonatomic, readwrite) uint32_t limit;

@end

#pragma mark - GetUserTrxListByTimeRequest

typedef GPB_ENUM(GetUserTrxListByTimeRequest_FieldNumber) {
  GetUserTrxListByTimeRequest_FieldNumber_Name = 1,
  GetUserTrxListByTimeRequest_FieldNumber_Start = 2,
  GetUserTrxListByTimeRequest_FieldNumber_End = 3,
  GetUserTrxListByTimeRequest_FieldNumber_LastTrx = 4,
  GetUserTrxListByTimeRequest_FieldNumber_Limit = 5,
};

@interface GetUserTrxListByTimeRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) account_name *name;
/** Test to see if @c name has been set. */
@property(nonatomic, readwrite) BOOL hasName;

@property(nonatomic, readwrite, strong, null_resettable) time_point_sec *start;
/** Test to see if @c start has been set. */
@property(nonatomic, readwrite) BOOL hasStart;

@property(nonatomic, readwrite, strong, null_resettable) time_point_sec *end;
/** Test to see if @c end has been set. */
@property(nonatomic, readwrite) BOOL hasEnd;

@property(nonatomic, readwrite, strong, null_resettable) TrxInfo *lastTrx;
/** Test to see if @c lastTrx has been set. */
@property(nonatomic, readwrite) BOOL hasLastTrx;

@property(nonatomic, readwrite) uint32_t limit;

@end

#pragma mark - GetUserTrxListByTimeResponse

typedef GPB_ENUM(GetUserTrxListByTimeResponse_FieldNumber) {
  GetUserTrxListByTimeResponse_FieldNumber_TrxListArray = 1,
};

@interface GetUserTrxListByTimeResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TrxInfo*> *trxListArray;
/** The number of items in @c trxListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger trxListArray_Count;

@end

#pragma mark - VoterOfPost

typedef GPB_ENUM(VoterOfPost_FieldNumber) {
  VoterOfPost_FieldNumber_AccountName = 1,
  VoterOfPost_FieldNumber_WeightedVp = 2,
};

@interface VoterOfPost : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) account_name *accountName;
/** Test to see if @c accountName has been set. */
@property(nonatomic, readwrite) BOOL hasAccountName;

@property(nonatomic, readwrite) uint64_t weightedVp;

@end

#pragma mark - GetPostInfoByIdRequest

typedef GPB_ENUM(GetPostInfoByIdRequest_FieldNumber) {
  GetPostInfoByIdRequest_FieldNumber_PostId = 1,
  GetPostInfoByIdRequest_FieldNumber_VoterListLimit = 2,
  GetPostInfoByIdRequest_FieldNumber_ReplyListLimit = 3,
};

@interface GetPostInfoByIdRequest : GPBMessage

@property(nonatomic, readwrite) uint64_t postId;

@property(nonatomic, readwrite) uint32_t voterListLimit;

@property(nonatomic, readwrite) uint32_t replyListLimit;

@end

#pragma mark - GetPostInfoByIdResponse

typedef GPB_ENUM(GetPostInfoByIdResponse_FieldNumber) {
  GetPostInfoByIdResponse_FieldNumber_PostInfo = 1,
  GetPostInfoByIdResponse_FieldNumber_VoterListArray = 2,
  GetPostInfoByIdResponse_FieldNumber_ReplyListArray = 3,
};

@interface GetPostInfoByIdResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) PostResponse *postInfo;
/** Test to see if @c postInfo has been set. */
@property(nonatomic, readwrite) BOOL hasPostInfo;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<VoterOfPost*> *voterListArray;
/** The number of items in @c voterListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger voterListArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PostResponse*> *replyListArray;
/** The number of items in @c replyListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger replyListArray_Count;

@end

#pragma mark - GetContractInfoRequest

typedef GPB_ENUM(GetContractInfoRequest_FieldNumber) {
  GetContractInfoRequest_FieldNumber_Owner = 1,
  GetContractInfoRequest_FieldNumber_ContractName = 2,
  GetContractInfoRequest_FieldNumber_FetchAbi = 3,
  GetContractInfoRequest_FieldNumber_FetchCode = 4,
};

@interface GetContractInfoRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) account_name *owner;
/** Test to see if @c owner has been set. */
@property(nonatomic, readwrite) BOOL hasOwner;

@property(nonatomic, readwrite, copy, null_resettable) NSString *contractName;

@property(nonatomic, readwrite) BOOL fetchAbi;

@property(nonatomic, readwrite) BOOL fetchCode;

@end

#pragma mark - GetContractInfoResponse

typedef GPB_ENUM(GetContractInfoResponse_FieldNumber) {
  GetContractInfoResponse_FieldNumber_Exist = 1,
  GetContractInfoResponse_FieldNumber_Abi = 2,
  GetContractInfoResponse_FieldNumber_Code = 3,
};

@interface GetContractInfoResponse : GPBMessage

@property(nonatomic, readwrite) BOOL exist;

@property(nonatomic, readwrite, copy, null_resettable) NSString *abi;

@property(nonatomic, readwrite, copy, null_resettable) NSData *code;

@end

#pragma mark - GetBlkIsIrreversibleByTxIdRequest

typedef GPB_ENUM(GetBlkIsIrreversibleByTxIdRequest_FieldNumber) {
  GetBlkIsIrreversibleByTxIdRequest_FieldNumber_TrxId = 1,
};

@interface GetBlkIsIrreversibleByTxIdRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) sha256 *trxId;
/** Test to see if @c trxId has been set. */
@property(nonatomic, readwrite) BOOL hasTrxId;

@end

#pragma mark - GetBlkIsIrreversibleByTxIdResponse

typedef GPB_ENUM(GetBlkIsIrreversibleByTxIdResponse_FieldNumber) {
  GetBlkIsIrreversibleByTxIdResponse_FieldNumber_Result = 1,
};

@interface GetBlkIsIrreversibleByTxIdResponse : GPBMessage

@property(nonatomic, readwrite) BOOL result;

@end

#pragma mark - GetAccountListByCreTimeRequest

typedef GPB_ENUM(GetAccountListByCreTimeRequest_FieldNumber) {
  GetAccountListByCreTimeRequest_FieldNumber_Start = 1,
  GetAccountListByCreTimeRequest_FieldNumber_End = 2,
  GetAccountListByCreTimeRequest_FieldNumber_LastAccount = 3,
  GetAccountListByCreTimeRequest_FieldNumber_Limit = 4,
};

@interface GetAccountListByCreTimeRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) time_point_sec *start;
/** Test to see if @c start has been set. */
@property(nonatomic, readwrite) BOOL hasStart;

@property(nonatomic, readwrite, strong, null_resettable) time_point_sec *end;
/** Test to see if @c end has been set. */
@property(nonatomic, readwrite) BOOL hasEnd;

@property(nonatomic, readwrite, strong, null_resettable) AccountInfo *lastAccount;
/** Test to see if @c lastAccount has been set. */
@property(nonatomic, readwrite) BOOL hasLastAccount;

@property(nonatomic, readwrite) uint32_t limit;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
